{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8081",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/accounts/{id}": {
      "get": {
        "tags": [
          "cuenta-controlador"
        ],
        "summary": "Obtener una cuenta por ID",
        "description": "Este endpoint devuelve los detalles de una cuenta específica mediante su ID.",
        "operationId": "getById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cuenta encontrada exitosamente",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          },
          "404": {
            "description": "Cuenta no encontrada",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "cuenta-controlador"
        ],
        "summary": "Actualizar una cuenta",
        "description": "Este endpoint permite actualizar los detalles de una cuenta existente mediante su ID.",
        "operationId": "updateAccount",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/InputCuentaUpdateDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Cuenta actualizada exitosamente",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          },
          "400": {
            "description": "Datos de entrada inválidos",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          },
          "404": {
            "description": "Cuenta no encontrada",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "cuenta-controlador"
        ],
        "summary": "Eliminar una cuenta",
        "description": "Este endpoint elimina una cuenta específica mediante su ID.",
        "operationId": "deleteAccount",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cuenta eliminada exitosamente",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          },
          "404": {
            "description": "Cuenta no encontrada",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          }
        }
      }
    },
    "/api/accounts": {
      "get": {
        "tags": [
          "cuenta-controlador"
        ],
        "summary": "Obtener todas las cuentas",
        "description": "Este endpoint devuelve una lista de todas las cuentas registradas.",
        "operationId": "getCuentas",
        "responses": {
          "200": {
            "description": "Lista de cuentas obtenida con éxito",
            "content": {
              "application/hal+json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/OutputCuentaDTO"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error interno del servidor",
            "content": {
              "application/hal+json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/OutputCuentaDTO"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "cuenta-controlador"
        ],
        "summary": "Crea una nueva cuenta",
        "description": "Este endpoint permite crear una nueva cuenta asociada a un usuario. Se debe proporcionar toda la información requerida.",
        "operationId": "createAccount",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/InputCuentaDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Cuenta creada exitosamente",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          },
          "400": {
            "description": "Solicitud incorrecta",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          }
        }
      }
    },
    "/api/accounts/update-balance/{id}": {
      "patch": {
        "tags": [
          "cuenta-controlador"
        ],
        "summary": "Actualizar saldo de una cuenta",
        "description": "Este endpoint permite actualizar el saldo de una cuenta específica.",
        "operationId": "updateSaldo",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AccountBalanceDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Saldo actualizado exitosamente",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          },
          "404": {
            "description": "Cuenta no encontrada",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          }
        }
      }
    },
    "/api/accounts/management": {
      "patch": {
        "tags": [
          "cuenta-controlador"
        ],
        "summary": "Gestionar disponibilidad de una cuenta",
        "description": "Este endpoint permite gestionar la disponibilidad de una cuenta.",
        "operationId": "manageAccount",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AccountAvailabilityDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Disponibilidad gestionada exitosamente",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          },
          "404": {
            "description": "Cuenta no encontrada",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          }
        }
      }
    },
    "/api/accounts/ownerEmail/{ownerEmail}": {
      "get": {
        "tags": [
          "cuenta-controlador"
        ],
        "summary": "Obtener cuenta por email del propietario",
        "description": "Este endpoint devuelve la cuenta asociada al email de un propietario específico.",
        "operationId": "getByOwnerEmail",
        "parameters": [
          {
            "name": "ownerEmail",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cuenta obtenidas con éxito",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          },
          "404": {
            "description": "No se encontraro cuenta para el email proporcionado",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/OutputCuentaDTO"
                }
              }
            }
          }
        }
      }
    },
    "/api/accounts/emailAvailable": {
      "get": {
        "tags": [
          "cuenta-controlador"
        ],
        "summary": "Verificar disponibilidad de email",
        "description": "Este endpoint verifica si un email está disponible para asociarse a una nueva cuenta.",
        "operationId": "checkEmail",
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Email verificado con éxito",
            "content": {
              "application/hal+json": {
                "schema": {
                  "type": "boolean"
                }
              }
            }
          },
          "400": {
            "description": "Solicitud incorrecta",
            "content": {
              "application/hal+json": {
                "schema": {
                  "type": "boolean"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "InputCuentaUpdateDTO": {
        "type": "object",
        "properties": {
          "saldo": {
            "type": "number",
            "format": "double"
          },
          "cuentaMP": {
            "type": "string"
          },
          "isDisable": {
            "type": "boolean"
          }
        }
      },
      "OutputCuentaDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "fechaAlta": {
            "type": "string",
            "format": "date"
          },
          "saldo": {
            "type": "number",
            "format": "double"
          },
          "cuentaMP": {
            "type": "string"
          },
          "isDisable": {
            "type": "boolean"
          },
          "ownerEmail": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "usuarios": {
            "uniqueItems": true,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OutputUserDTO"
            }
          }
        }
      },
      "OutputUserDTO": {
        "type": "object",
        "properties": {
          "idUser": {
            "type": "integer",
            "format": "int64"
          },
          "nombre": {
            "type": "string"
          },
          "apellido": {
            "type": "string"
          },
          "latitud": {
            "type": "number",
            "format": "double"
          },
          "longitud": {
            "type": "number",
            "format": "double"
          }
        }
      },
      "InputCuentaDTO": {
        "type": "object",
        "properties": {
          "ctaMP": {
            "type": "string"
          },
          "nombreUsuario": {
            "type": "string"
          },
          "apellidoUsuario": {
            "type": "string"
          },
          "celularUsuario": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "saldo": {
            "type": "number",
            "format": "double"
          },
          "isDisable": {
            "type": "boolean"
          }
        }
      },
      "AccountBalanceDTO": {
        "type": "object",
        "properties": {
          "saldo": {
            "type": "number",
            "format": "double"
          }
        }
      },
      "AccountAvailabilityDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "available": {
            "type": "boolean"
          }
        }
      }
    }
  }
}