spring:
  cloud:
    gateway:
      routes:
        - id: scooter-service
          uri: http://localhost:8082  # Corregir la URL de scooters
          predicates:
            - Path=/api/scooters/**
        - id: trip-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/trips/**
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/accounts/**
        - id: report-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/reportes/**
  security:
    user:
      name: admin
      password: admin123

server:
  port: 4000
